version: '3.9'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 80
      NORKOS-AUTH-TOKEN: local-one-will-be-overwritten
    ports:
      - 8000:80 #localhost:Dockerfile
    volumes:
      - .:/app
