version: '3.9'
services:

  rabbitmq:
    image: 'rabbitmq:3.10-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 80
      AUTH_TOKEN: local
      TWO_FA: local_2fa
      CLOUDAMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      ASYNC_DB_URL : 'postgresql+asyncpg://postgres_user:postgres_pass@db:5432/postgres'
      ENABLE_EVENTS : 'True'
      DEBUG_LOGGER_LEVEL : 'True'
      DEBUG_REST : 'True'
    ports:
      - '8080:80' #localhost:Dockerfile
    volumes:
      - .:/app
    networks:
      - network

  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network

networks:
  network: {}

volumes:
  db:
