version: '3.9'
services:

  rabbitmq:
    image: 'rabbitmq:3.10-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
       # HTTP management UI
      - '15672:15672'
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 80
      NORKOS-AUTH-TOKEN: local-one-will-be-overwritten
      CLOUDAMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    ports:
      - 8000:80 #localhost:Dockerfile
    volumes:
      - .:/app
    networks:
      - network

  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile
    environment:
      PORT: 70
      CLOUDAMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    ports:
      - 8080:70 #localhost:Dockerfile
    networks:
      - network

networks:
  network: {}
