# pylint: skip-file
"""agent can be blocked

Revision ID: 00c427e59a9a
Revises: e3ce0f243521
Create Date: 2022-12-06 15:41:15.993507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c427e59a9a'
down_revision = 'e3ce0f243521'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('blocked', sa.Boolean(), nullable=False, server_default=str(False)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'blocked')
    # ### end Alembic commands ###
