# pylint: skip-file
"""account_for_vip

Revision ID: e131f7813c2e
Revises: 00c427e59a9a
Create Date: 2022-12-12 10:23:41.682422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e131f7813c2e'
down_revision = '00c427e59a9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('vip', sa.Boolean(), nullable=False, server_default=str(False)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'vip')
    # ### end Alembic commands ###
