# pylint: skip-file
"""extend account with region

Revision ID: e3ce0f243521
Revises: 0f71bbb218e0
Create Date: 2022-12-06 11:41:51.161190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import acm_service.sql_app.schemas

revision = 'e3ce0f243521'
down_revision = '0f71bbb218e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('region', sa.String(), nullable=False,
                                        server_default=acm_service.sql_app.schemas.RegionEnum.nam))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'region')
    # ### end Alembic commands ###
